name: "🎨 design"
description: "UI/UX, 컴포넌트, 화면 디자인 개선 (제목은 'design: 화면 디자인 구성' 형태로 입력해 주세요)"

title: "design: "
labels: ["design"]
body:
  - type: textarea
    attributes:
      label: 🎯 목적
      description: |
        어떤 디자인 작업이 필요한지 개요를 설명해 주세요.
        예: 메인 페이지 레이아웃 개선, 로그인 페이지 UI 리뉴얼, 버튼 컴포넌트 디자인 개선
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🖼️ 디자인 요구사항
      description: |
        구체적인 디자인 요구사항을 작성해 주세요.  
        필요하다면 체크박스 형태로 세부 항목을 추가하세요.
        예:
        - [ ] 메인 Hero 섹션의 배경 이미지 교체
        - [ ] 반응형 디자인 개선
        - [ ] 공통 버튼 스타일 가이드 정리
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📎 참고 자료
      description: |
        Figma 링크, 레퍼런스 UI, 이미지, 참고 사이트 등을 추가해 주세요.  
        참고 자료가 없다면 `_No response_`로 작성해 주세요.
      placeholder: |
        예:
        - Figma: https://figma.com/...
        - 참고 사이트: https://dribbble.com/...
        - 기존 UI 캡처 이미지 첨부
    validations:
      required: false

  - type: textarea
    attributes:
      label: 🔄 예상 영향 범위
      description: |
        해당 디자인 변경이 영향을 줄 수 있는 화면, 컴포넌트, 문서 등을 작성해 주세요.
        예:
        - Header 컴포넌트 스타일 변경
        - 전체 라우팅 구조에 영향 없음
        - 다크모드 스타일 업데이트 필요
    validations:
      required: false
